package edu.mit.scansite.sql.constants;

public enum AvailableStatements {
    DATA_SOURCES_DISPLAY_NAME_STATEMENT,
    DATA_SOURCE_NAMES_STATEMENT,
    MOTIF_DISPLAY_NAMES_STATEMENT,
    MOTIF_GROUP_DISPLAY_NAMES_STATEMENT,
    PROTEIN_IDENTIFIER_STATEMENT_ENSEMBL_HUMAN,
    PROTEIN_IDENTIFIER_STATEMENT_ENSEMBL_MOUSE,
    PROTEIN_IDENTIFIER_STATEMENT_SWISSPROT,
    PROTEIN_IDENTIFIER_STATEMENT_YEAST
}
